import './globals.css';
import type { Metadata } from 'next';
import IntegralCF from './_fonts/integral-cf/font';
import Geist from './_fonts/geist/font';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import Provider from '@/lib/provider/provider';
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: 'Clothy - Shop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${IntegralCF.variable} ${Geist.variable} bg-primary-0 font-geist font-normal text-primary-900 antialiased selection:bg-primary-900 selection:text-primary-50`}
      >
        <Provider>
          <NextTopLoader color="#a4a4a4" showSpinner={false} shadow={false} />
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
